# Generated by Django 4.2.4 on 2023-08-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men',
            name='photo',
        ),
    ]
